#https://github.com/marketplace/actions/github-tag-bump
name: Add Tag
on:
  push:
    branches:
      - master
    #types: [closed]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - if: github.event.pull_request.merged == true
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        
 
